{
 "title": "OpenStack Project Metrics",
 "tags": [
  "capacity",
  "azimuth"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "project_id", "label": "Project", "query": { "query": "openstack_project_usage" } }
  ]
 },
 "panels": [
  { "title": "Project Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(openstack_project_usage{project_id=~\"${project_id}\"}) by (placement_resource)",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  {
   "title": "Resources per Project",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(openstack_project_usage{project_id=~\"${project_id}\"}) by (placement_resource)",
     "legendFormat": "{{placement_resource}}"
    }
   ]
  },
  {
   "title": "Project quota",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openstack_project_quota{project_id=~\"${project_id}\"}",
     "legendFormat": "{{project_name}}:{{quota_resource}}"
    }
   ]
  },
  {
   "title": "Servers by flavor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count(libvirt_domain_info_meta{project_id=~\"${project_id}\"}) by (domain,flavor)) by (flavor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_vcpu_time_seconds_total{}[5m]) / ignoring(instance,vcpu) group_left(domain) libvirt_domain_info_virtual_cpus{}) by (domain) * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_info_meta{project_id=~\"${project_id}\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Memory utilization per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_used_percent * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_info_meta{project_id=~\"${project_id}\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Disk utilization per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_time_seconds_total[5m]) * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_info_meta{project_id=~\"${project_id}\"}",
     "legendFormat": "{{instance_name}} : read {{target_device}}"
    },
    {
     "expr": "rate(libvirt_domain_block_stats_write_time_seconds_total[5m]) * on(domain) group_left(instance_name,project_name,project_id) libvirt_domain_info_meta{project_id=~\"${project_id}\"} * -1",
     "legendFormat": "{{instance_name}} : write {{target_device}}"
    }
   ]
  },
  { "title": "Per Hypervisor Free Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Free Capacity by Flavor",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_free_capacity_by_flavor_total",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  }
 ]
}