{
 "title": "Cloud Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary Hypervisor Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Memory",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(openstack_hypervisor_placement_allocatable_capacity{resource=\"MEMORY_MB\"} - on(hypervisor) openstack_hypervisor_placement_allocated{resource=\"MEMORY_MB\"})",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "SUM(openstack_hypervisor_placement_allocated{resource=\"MEMORY_MB\"})",
     "legendFormat": "Allocated Memory"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(openstack_hypervisor_placement_allocatable_capacity{resource=\"VCPU\"} - on(hypervisor) openstack_hypervisor_placement_allocated{resource=\"VCPU\"})",
     "legendFormat": "Free VCPU"
    },
    {
     "expr": "SUM(openstack_hypervisor_placement_allocatable_capacity{resource=\"PCPU\"} - on(hypervisor) openstack_hypervisor_placement_allocated{resource=\"PCPU\"})",
     "legendFormat": "Free PCPU"
    },
    {
     "expr": "SUM(openstack_hypervisor_placement_allocated{resource=\"VCPU\"})",
     "legendFormat": "Allocated VCPU"
    },
    {
     "expr": "SUM(openstack_hypervisor_placement_allocated{resource=\"PCPU\"})",
     "legendFormat": "Allocated PCPU"
    }
   ]
  },
  {
   "title": "Total Local Disk",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(openstack_hypervisor_placement_allocatable_capacity{resource=\"DISK_GB\"} - on(hypervisor) openstack_hypervisor_placement_allocated{resource=\"DISK_GB\"})",
     "legendFormat": "Free Local Disk"
    },
    {
     "expr": "SUM(openstack_hypervisor_placement_allocated{resource=\"DISK_GB\"})",
     "legendFormat": "Allocated Local Disk"
    }
   ]
  },
  {
   "title": "Free Capacity by Flavor",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_free_capacity_by_flavor_total",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  { "title": "Project Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory Used by Project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "openstack_project_usage{placement_resource=\"MEMORY_MB\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "CPUs Used by Project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "openstack_project_usage{placement_resource=\"VCPU\"}",
     "legendFormat": "VCPU {{project_name}}"
    },
    {
     "expr": "openstack_project_usage{placement_resource=\"PCPU\"}",
     "legendFormat": "PCPU {{project_name}}"
    }
   ]
  },
  { "title": "Per Hypervisor Free Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Free Capacity by Flavor and AZ",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(openstack_free_capacity_hypervisor_by_flavor) by (flavor_name, az_aggregate)",
     "legendFormat": "{{az_aggregate}} : {{flavor_name}} "
    }
   ]
  },
  {
   "title": "Memory Free by Hypervisor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "openstack_hypervisor_placement_allocatable_capacity{resource=\"MEMORY_MB\"} - on(hypervisor) openstack_hypervisor_placement_allocated{resource=\"MEMORY_MB\"}",
     "legendFormat": "{{hypervisor}}"
    }
   ]
  }
 ]
}